# Generated by Django 3.0.8 on 2020-07-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='poll.Question'),
            preserve_default=False,
        ),
    ]
